gText_WouldYouLikeToRestYourPkmn::
	.string "Welcome to the POKéMON CENTER.\p"
	.string "We'll patch your whole team up,\n"
	.string "no copay, no wait.\p"
	.string "Rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "You got it. Two seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "All set -- good as new.\p"
	.string "Stay safe out there.$"

gText_WeHopeToSeeYouAgain::
	.string "Take care of yourself!$"

gText_WelcomeCutShort::
	.string "Welcome to the POKéMON CENTER.\p"
	.string "We'll patch your whole team up,\n"
	.string "no copay, no wait.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen plenty of TRAINERS with\n"
	.string "a SILVER CARD, but, {PLAYER},\l"
	.string "you're the first GOLD CARD\l"
	.string "I've ever laid eyes on!\p"
	.string "Okay, {PLAYER}, allow me the honor\n"
	.string "of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "Good to see you, {PLAYER}!\n"
	.string "The usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "You got it. Two seconds.$"

gText_ThankYouForWaiting::
	.string "Thanks for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "Take care of yourself!$"
