gText_HowMayIServeYou::
	.string "Yeah, welcome in.\p"
	.string "What'll it be?$"

gText_PleaseComeAgain::
	.string "Aight. Take it easy.$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}! Welcome in.\p"
	.string "What'll it be?$"

Pokemart_DefaultItemList::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	pokemartlistend
