LittlerootTown_MapScripts::
	.byte 0

LittlerootTown_EventScript_SAGJared::
	msgbox LittlerootTown_Text_SAGJared, MSGBOX_NPC
	end

LittlerootTown_Text_SAGJared:
	.string "Shane! It's your brother.\n"
	.string "Apt 11I, same as always.\p"
	.string "Took you long enough to wake up.\n"
	.string "That Eevee I gave you? Don't waste it.\p"
	.string "Sixteen gyms between you and me.\n"
	.string "I'll be waiting at the top. Go.$"

LittlerootTown_EventScript_SAGDoorman::
	msgbox LittlerootTown_Text_SAGDoorman, MSGBOX_NPC
	end

LittlerootTown_Text_SAGDoorman:
	.string "Mornin', Mr. Gaer.\n"
	.string "Welcome to Hudson Yards.\p"
	.string "Head south for Times Square when\n"
	.string "you're ready. Whole city's waiting.$"
